#pragma autorecover
#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\WMI")

[Dynamic,
 Description("Refsv1WppTrace"),
 guid("{6d2fd9c5-8bd8-4a5d-8aa8-01e5c3b2ae23}"),
 locale("MS\\0x409")]
class Refsv1WppTrace : EventTrace
{
    [Description ("Enable Flags") : amended,
        ValueDescriptions{
             "FATAL Flag",
             "ERROR Flag",
             "WARNING Flag",
             "READ Flag",
             "WRITE Flag",
             "COMPRESSED Flag",
             "EFS Flag",
             "MFT Flag",
             "VOLBITMAP Flag",
             "CREATE Flag",
             "ALTSTREAMS Flag",
             "OBJID Flag",
             "INDEXES Flag",
             "TXFKTM Flag",
             "TXFRECOVERY Flag",
             "TXFRM Flag",
             "TXFFCB Flag",
             "SELFHEAL Flag",
             "HEALBITMAP Flag",
             "USNJRNL Flag",
             "DELNOTIFY Flag",
             "MINSTORE Flag",
             "SCRUB Flag",
             "TREEUPDATE Flag"},
        DefineValues{
             "FATAL",
             "ERROR",
             "WARNING",
             "READ",
             "WRITE",
             "COMPRESSED",
             "EFS",
             "MFT",
             "VOLBITMAP",
             "CREATE",
             "ALTSTREAMS",
             "OBJID",
             "INDEXES",
             "TXFKTM",
             "TXFRECOVERY",
             "TXFRM",
             "TXFFCB",
             "SELFHEAL",
             "HEALBITMAP",
             "USNJRNL",
             "DELNOTIFY",
             "MINSTORE",
             "SCRUB",
             "TREEUPDATE"},
        Values{
             "FATAL",
             "ERROR",
             "WARNING",
             "READ",
             "WRITE",
             "COMPRESSED",
             "EFS",
             "MFT",
             "VOLBITMAP",
             "CREATE",
             "ALTSTREAMS",
             "OBJID",
             "INDEXES",
             "TXFKTM",
             "TXFRECOVERY",
             "TXFRM",
             "TXFFCB",
             "SELFHEAL",
             "HEALBITMAP",
             "USNJRNL",
             "DELNOTIFY",
             "MINSTORE",
             "SCRUB",
             "TREEUPDATE"},
        ValueMap{
             "0x00000001",
             "0x00000002",
             "0x00000004",
             "0x00000008",
             "0x00000010",
             "0x00000020",
             "0x00000040",
             "0x00000080",
             "0x00000100",
             "0x00000200",
             "0x00000400",
             "0x00000800",
             "0x00001000",
             "0x00002000",
             "0x00004000",
             "0x00008000",
             "0x00010000",
             "0x00020000",
             "0x00040000",
             "0x00080000",
             "0x00100000",
             "0x00200000",
             "0x00400000",
             "0x00800000"}: amended
    ]
    uint32 Flags;
};

